on:
  push:
    branches:
      - '*'

jobs:
  composer-normalize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: mbstring
          php-version: 8.3

      - uses: ramsey/composer-install@v3

      - run: composer normalize

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Normalize composer.json

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write --tab-width=2 *.md **/*.md
          branch: ${{ github.head_ref }}
          commit_message: Prettify docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
